name: Build and test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    # todo: @skyegalaxy - add back once rclcpp w/ CBG Executor is available on kilted
    continue-on-error: ${{ matrix.ros == 'kilted' }}
    strategy:
      fail-fast: false
      matrix:
        ros: [jazzy, kilted, lyrical, rolling]
        include:
          - ros: jazzy
            ubuntu: noble
          - ros: kilted
            ubuntu: noble
          - ros: lyrical
            ubuntu: resolute
          - ros: rolling
            ubuntu: resolute
    name: ${{ matrix.ros }}
    container:
      image: ghcr.io/ros-tooling/setup-ros-docker/setup-ros-docker-ubuntu-${{ matrix.ubuntu }}:latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ros-tooling/action-ros-ci@v0.4
        id: action_ros_ci_step
        with:
          target-ros2-distro: ${{ matrix.ros }}
          import-token: ${{ secrets.REPO_TOKEN }}
          package-name:
            composition_benchmark
            irobot_benchmark
            irobot_interfaces_plugin
            performance_metrics
            performance_test
            performance_test_examples
            performance_test_factory
            performance_test_msgs
            performance_test_plugin_cmake
            memory_benchmark
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: colcon-logs-${{ matrix.ros }}
          path: ros_ws/log
